-- Create users
CREATE USER '${READ_USER}' IDENTIFIED BY '${READ_PASS}';
CREATE USER '${INSERTER}' IDENTIFIED BY '${INSERT_PASS}';

-- Grant privileges
GRANT LOCK TABLES ON ${DB_NAME}.* TO '${READ_USER}';
GRANT SELECT ON ${DB_NAME}.* TO '${READ_USER}';
GRANT INSERT ON ${DB_NAME}.* TO '${INSERTER}';
GRANT SELECT ON ${DB_NAME}.* TO '${INSERTER}';
GRANT UPDATE (Location) ON ${DB_NAME}.Board to '${INSERTER}';
