INSERT INTO `People` VALUES
       (16,'Bryan'),
       (18,'Adam'),
       (22,'Rand'),
       (23,'Seth'),
       (24,'Nick Shimota'),
       (25,'Charlie Kapsiak'),
       (26,'Billy'),
       (27,'Joe G'),
       (28,'Jeremy M'),
       (29,'Eva Adhikari'),
       (30,'Devin Mahon'),
       (31,'Jocie H'),
       (32,'Sudhanva M'),
       (33,'Sarah A'),
       (34,'Nadja'),
       (35,'Josephine'),
       (36,'Josephine'),
       (37,'Hunter J'),
       (38,'Hunter J'),
       (39,'Jacob W'),
       (40,'Jacob W'),
       (41,'Sam P');

INSERT INTO `Manufacturers` VALUES
       (1,'APCT-Caltronics'),
       (2,'Sunshine-Caltronics'),
       (3,'TTM-Caltronics'),
       (4,'Sunshine-ProtoServices'),
       (5,'PCBWay-PCBWay'),
       (6,'Sunshine-Poly'),
       (7,'JLBPCB-Caltronics'),
       (8,'JLBPCB-Evotronics'),
       (9,'Sunshine-Piranha'),
       (10,'Sunshine-Evotronics');
