INSERT INTO `People` VALUES
     (9,'Charlie Kapsiak'),
     (11,'Rand'),
     (12,'Billy'),
     (14,'Seth'),
     (15,'Nick Shimota'),
     (16,'Bryan'),
     (17,'Adam'),
     (18,'Joe G'),
     (19,'Jeremy M'),
     (20,'Eva Adhikari'),
     (21,'Devin Mahon'),
     (22,'Jocie H'),
     (23,'Sudhanva M'),
     (24,'Nadja'),
     (25,'Nadja'),
     (26,'Nadja S'),
     (27,'Nadja S'),
     (28,'Sarah A'),
     (29,'Sarah A'),
     (30,'Josephine'),
     (31,'Hunter J'),
     (32,'Hunter J'),
     (33,'Jacob W'),
     (34,'Jacob W'),
     (35,'Sam P');

INSERT INTO `Manufacturers` VALUES
     (1,'APCT-Caltronics'),
     (2,'Sunshine-Caltronics'),
     (3,'TTM-Caltronics'),
     (4,'Sunshine-ProtoServices'),
     (5,'PCBWay-PCBWay'),
     (6,'Sunshine-Poly'),
     (7,'JLBPCB-Caltronics'),
     (8,'JLBPCB-Evotronics'),
     (9,'Sunshine-Piranha'),
     (10,'Sunshine-Evotronics');
